# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: babblesim
      url-base: https://github.com/BabbleSim
    - name: vaishnavachath
      url-base: https://github.com/vaishnavachath
    - name: jkridner
      url-base: https://git.beagleboard.org/jkridner
    - name: beagleconnect
      url-base: https://git.beagleboard.org/beagleconnect/zephyr
    - name: beagleplay
      url-base: https://git.beagleboard.org/beagleplay/cc1352
    - name: gsoc-greybus
      url-base: https://git.beagleboard.org/gsoc/greybus

  group-filter: [-babblesim, -optional]

  #
  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
      path: modules/hal/cmsis
      groups:
        - hal
    - name: hal_ti
      revision: b85f86e51fc4d47c4c383d320d64d52d4d371ae4
      path: modules/hal/ti
      groups:
        - hal
    - name: littlefs
      path: modules/fs/littlefs
      groups:
        - fs
      revision: ca583fd297ceb48bced3c2548600dc615d67af24
    - name: mbedtls
      revision: 7053083b0cff8462464e3cbb826e87852fc03da6
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      revision: e9131ee8b8ab9306d8f6ad410fd1e3d8a820ce10
      path: bootloader/mcuboot
    - name: net-tools
      revision: 3a677d355cc7f73e444801a6280d0ccec80a1957
      path: tools/net-tools
      groups:
        - tools
    - name: picolibc
      path: modules/lib/picolibc
      revision: 1a5c603b9f8e228f9459bdafedad15ea28efc700
    - name: tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
      path: modules/crypto/tinycrypt
      groups:
        - crypto
    - name: trusted-firmware-m
      revision: 33c0f47bcb19721a5c33e6fe1eee9225d00bb5bc
      path: modules/tee/tf-m/trusted-firmware-m
      groups:
        - tee
    - name: zcbor
      revision: 67fd8bb88d3136738661fa8bb5f9989103f4599e
      path: modules/lib/zcbor
    - name: greybus-for-zephyr
      submodules: true
      remote: beagleconnect
      revision: 5e30fa667b0604655a40855a4070aab2a70a450f
      path: modules/greybus
    - name: wpanusb
      remote: beagleplay
      path: modules/wpanusb
      revision: e85d480a636b88d177aa2130f9df05e666c817c0
    - name: micropython
      remote: beagleconnect
      path: modules/micropython
      revision: c40256d06fa60d6b0740a5541bc40094bbb2e053
    - name: arduino-core
      remote: beagleconnect
      path: modules/lib/Arduino-Zephyr-API
      revision: 62c0ed927af7de74523f98e7b96489275cc77330
    - name: ClosedCube_OPT3001_Arduino
      remote: jkridner
      path: modules/lib/ClosedCube_OPT3001_Arduino
      revision: 96eaad9443fc833c08b1b61bb8b54b7acded6e06
    - name: cc1352-firmware
      remote: gsoc-greybus
      path: modules/greybus-host
      revision: 9a5b0fa15cc9128c6a64e13c4d95336bb8593dc9

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
