# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: vaishnavachath
      url-base: https://github.com/vaishnavachath
    - name: beagleconnect
      url-base: https://git.beagleboard.org/beagleconnect/zephyr
    - name: beagleplay
      url-base: https://git.beagleboard.org/beagleplay/cc1352

  #
  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      revision: 74981bf893e8b10931464b9945e2143d99a3f0a3
      path: modules/hal/cmsis
      groups:
        - hal
    - name: edtt
      revision: 000fb87261beaf33f80a8868e73857bd62edc668
      path: tools/edtt
      groups:
        - tools
    - name: fatfs
      revision: 89f53db0207cdcea5bd9bdd64acc3e1ed9a65b15
      path: modules/fs/fatfs
      groups:
        - fs
    - name: hal_ti
      revision: 4e0e053f5ea413ef0cb20000729038d921ac2746
      path: modules/hal/ti
      groups:
        - hal
    - name: libmetal
      revision: efa2ace6028290ddee494a78ade772a0b112ab83
      path: modules/hal/libmetal
      groups:
        - hal
    - name: liblc3
      revision: 448f3de31f49a838988a162ef1e23a89ddf2d2ed
      path: modules/lib/liblc3
    - name: littlefs
      path: modules/fs/littlefs
      groups:
        - fs
      revision: ca583fd297ceb48bced3c2548600dc615d67af24
    - name: lvgl
      revision: 5ab83099854719ed326b6ecb9b09b07b1eee4818
      path: modules/lib/gui/lvgl
    - name: lz4
      revision: 8e303c264fc21c2116dc612658003a22e933124d
      path: modules/lib/lz4
    - name: mbedtls
      revision: 4e1f66df894dc622da7bcd3884016a6ace08e9ea
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      revision: 59624334748129cb93f096408911a227b0dd64c0
      path: bootloader/mcuboot
    - name: net-tools
      revision: e0828aa9629b533644dc96ff6d1295c939bd713c
      path: tools/net-tools
      groups:
        - tools
    - name: open-amp
      revision: aedcc262f93bbb1b0c2f58026911575729b7465c
      path: modules/lib/open-amp
    - name: openthread
      revision: 1f1a826d1891fc99d14822abc0a1de257e9c6e9b
      path: modules/lib/openthread
    - name: picolibc
      path: modules/lib/picolibc
      revision: 0694a78fc08b3300c7db79602c46ba0a64428c8e
    - name: segger
      revision: e2ff2200556e8a8f962921444275c04971a2bb3d
      path: modules/debug/segger
      groups:
        - debug
    - name: sof
      revision: 6f5f7258ad2738df78e600568d38fc261e2a118d
      path: modules/audio/sof
    - name: tflite-micro
      revision: 9156d050927012da87079064db59d07f03b8baf6
      path: modules/lib/tflite-micro
      repo-path: tflite-micro
    - name: tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
      path: modules/crypto/tinycrypt
      groups:
        - crypto
    - name: TraceRecorderSource
      revision: d92607521335eaaaedb01b241cdd26fda48a5ca6
      path: modules/debug/TraceRecorder
      groups:
        - debug
    - name: trusted-firmware-m
      revision: 13abde213930ffdf600cf8f01113da8a5fdd9d9c
      path: modules/tee/tf-m/trusted-firmware-m
      groups:
        - tee
    - name: zcbor
      revision: 0.6.0
      path: modules/lib/zcbor
    - name: greybus-for-zephyr
      submodules: true
      remote: beagleconnect
      revision: 7a0de5d4db440b3366f0658812cd8fbd26b32cf3
      path: modules/greybus
    - name: wpanusb
      remote: beagleplay
      path: modules/wpanusb
      revision: fe1492f13319c64042eda1fda73932b0c6e8ed2f
    - name: micropython
      remote: beagleconnect
      path: modules/micropython
      revision: c40256d06fa60d6b0740a5541bc40094bbb2e053

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
